#!/usr/bin/env python
# Run:
#    dig google.com @localhost -p 2053
# to see if dnscrypt is able to resolve addresses. This should be run with the
# base check-dnscrypt-resolver; it should find an error earlier than the
# original script. May want combine these two scripts eventually.

from __future__ import print_function
from subprocess import Popen, PIPE
import socket
import os
import sys

MAINTAINER = 'root@localhost'

try:
    dig = Popen(
        'dig google.com @localhost -p 2053'.split(),
        stdout=PIPE
    )
    status = dig.wait()
except (IOError, OSError) as error:
    sys.exit(str(error))

if status:
    hostname = socket.gethostname().split('.')[0]
    subject = 'dnscrypt on %s' % hostname
    message = 'dnscrypt fails to resolve google.com on %s' % hostname
    try:
        process = Popen(['mail', '-s', subject, MAINTAINER], stdin=PIPE)
    except (IOError, OSError) as error:
        sys.exit(str(error))
    process.stdin.write(message)
    process.stdin.close()
    status = process.wait()
    if status != 0:
        print('mail: unexpected exit status (%s)' % status)
    sys.exit()
