#!/usr/bin/env python
#   Nov  1 05:29:02 host dnscrypt-proxy[818]: No useable certificates found
# in /var/log/messages. These indicate that the resolver used by dnscrypt has
# gone stale.  The date on these messages are checked (after reconstructing the
# year) and if they are newer than the modification date on the
# dnscrypt.service file a warning is mailed to the maintainer.

from __future__ import print_function
from subprocess import Popen, PIPE
from datetime import datetime
import socket
import os
import sys

MAINTAINER = 'root@localhost'

config_time = datetime.fromtimestamp(os.path.getmtime('/etc/systemd/system/dnscrypt.service'))

# In /var/log/messages look for messages of the form:
#    Nov  1 05:29:02 host dnscrypt-proxy[818]: No useable certificates found
with open('/var/log/messages', 'rU') as f:
    for line in f.readlines():
        if 'dnscrypt-proxy' in line and 'No useable certificates found' in line:
            current_time = datetime.now()
            msg_time = datetime.strptime(' '.join(line.split()[:3]), '%b %d %H:%M:%S')
            msg_year = 2015
            msg_time = msg_time.replace(year=msg_year)
            new_msg_time = msg_time
            while new_msg_time < current_time:
                msg_time = new_msg_time
                msg_year += 1
                new_msg_time = new_msg_time.replace(year=msg_year)
            if msg_time > config_time:
                hostname = socket.gethostname().split('.')[0]
                subject = 'dnscrypt failing on %s' % hostname
                message = line.strip()
                try:
                    process = Popen(['mail', '-s', subject, MAINTAINER], stdin=PIPE)
                except (IOError, OSError) as error:
                    sys.exit(str(error))
                process.stdin.write(message)
                process.stdin.close()
                status = process.wait()
                if status != 0:
                    print('mail: unexpected exit status (%s)' % status)
                sys.exit()
